# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qbZ3ERQauuRhf2Y2TbbuJlzgYeyKDo-5
"""

import pickle

# Load the model and vectorizer
with open("/content/spam_model.pkl", "rb") as f:
    model, vectorizer = pickle.load(f)

# Example usage
def predict_email(text):
    from re import sub
    cleaned = sub(r'[^a-zA-Z]', ' ', text).lower()
    vect = vectorizer.transform([cleaned])
    pred = model.predict(vect)[0]
    if pred == 1:
      return "The mail is Fake"
    if pred == 0:
      return "The mail is Real"
    return "Error"

print(predict_email(input("Enter The mail: ")))